### ISSUE TITLE
How to use wp-cli with this configuration?

### ISSUE THREAD

**Issue by michaelalhilly** [DockerIt/wordpress-docker#2]
Please add an example showing how to use wp-cli with this configuration. It seems it is setup to run from outside the container like this:

docker-compose run -rm wp-cli plugin install jetpack

However, this is returning the following notification:

Run a one-off command on a service.

**Comment by matt-t-d** [comment]
Hi,

That's exactly how I would like it to run but the WP CLI is still a work in progress and I haven't been able to put much extra time into this since it was created. I should be able too soon so I'll try to update soon

**Comment by michaelalhilly** [comment]
Ah no worries. Thanks for putting this together. It's the simplest configuration for containerizing WordPress so far. Very helpful in understanding how to use Docker with WP. I'll keep my eye on it and post a fix if I find one.

**Comment by michaelalhilly** [comment]
Closing old question.
